version: "3.7"

services:

    db:
        image: "postgres:${POSTGRES_VERSION}"
        restart: unless-stopped
        env_file: ./.env
        container_name: "postgres-${POSTGRES_VERSION}"
        tty: true

        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

        volumes:
            # - ./postgres/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
            - type: volume
              source: postgres_data
              target: /var/lib/postgresql/data
              volume:
                nocopy: true

        ports:
            - "${POSTGRES_PORT}:5432"
            
        networks:
            - env-network
    
    node:
        image: "node:${NODE_VERSION}"
        container_name: "node-${NODE_VERSION}"
        restart: unless-stopped
        user: "root"
        tty: true
        stdin_open: true
        env_file: ./.env
        working_dir: /home/node

        volumes:
            - ~/ReactProjects/:/home/node/react/
            - ~/JSProjects/:/home/node/js/
            - ~/LaravelProjects/:/home/node/laravel/

        environment:
            NODE_ENV: ${NODE_ENV}

        ports:
            - "${NODE_PORT}:8080"

        networks:
            - env-network

        depends_on:
            - db
            - php

    php:
        image: "php-${PHP_VERSION}-extended"
        container_name: "php-${PHP_VERSION}"
        restart: unless-stopped
        user: "root"
        stdin_open: true
        tty: true
        env_file: ./.env
        working_dir: /var/web

        build:
            context: ./php
            dockerfile: Dockerfile-${PHP_VERSION}
            args:
                PHP_VERSION: ${PHP_VERSION}

        volumes:
            - ~/PHPProjects/:/var/web/php/
            - ~/LaravelProjects/:/var/web/laravel/
            - ~/SymfonyProjects/:/var/web/symfony/

        ports:
            - "${PHP_PORT}:8000"

        depends_on:
            - db
            - rabbit

        networks:
            - env-network

    rabbit:
        image: "rabbitmq:${RABBITMQ_VERSION}"
        container_name: "rabbitmq-${RABBITMQ_VERSION}"
        restart: unless-stopped
        env_file: ./.env
        volumes:
            - type: volume
              source: rabbitmq_data
              target: /var/lib/rabbitmq/
              volume:
                nocopy: true

        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

        ports:
            - "${RABBITMQ_PORT}:5672"
            - "${RABBITMQ_PORT_MANAGMENT}:15672"

        networks:
            - env-network

    elastic:
        image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}"
        container_name: elastic-${ELASTICSEARCH_VERSION}
        restart: unless-stopped
        env_file: ./.env

        environment:
            - node.name=elastic
            - cluster.initial_master_nodes=elastic
            - MAX_MAP_COUNT=262144

        ulimits:
            memlock:
                soft: -1
                hard: -1
        
        volumes:
            - type: volume
              source: elastic_data
              target: /usr/share/elasticsearch/data
              volume:
                nocopy: true

        ports:
            - ${ELASTICSEARCH_PORT}:9200

        networks:
            - env-network

volumes:
    postgres_data:
    rabbitmq_data:
    elastic_data:

networks:
    env-network:
        driver: bridge