version: 3.7

services:

    db:
        image: "postgres:${POSTGRES_VERSION}"
        restart: always
        env_file: ./.env
        container_name: "postgres@${POSTGRES_VERSION}"
        tty: true
        entrypoint: ./postgres/entrypoint.sh

        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

        volumes:
            - type: volume
                source: postgres
                target: /var/lib/postgresql/data
                volume:
                    nocopy: true

        ports:
            - "${POSTGRES_PORT}:5432"
            
        networks:
            - app-network

volumes:
    postgres:

networks:
    env-network:
        driver: bridge