#!/bin/bash
set -a # automatically export all variables
source ~/DockerProjects/web-development-environment/.env
set +a
docker exec -i -w /var/web/symfony/payment-aggregator-service php-"$PHP_VERSION" composer "$@"